package intranet;

public enum FACULTY {
    INFORMATION_TECHNOLOGIES,
    BUSSINESS_SCHOOL,
    OIL_AND_GAS,
    MARITIME_ACADEMY,
    SCHOOL_OF_MATHEMATICS,
    SCHOOL_OF_ECONOMICS,
    CHEMICAL_ENGINEERING,
    GEOLOGICAL_EXPLORATION
}
